apiVersion: apps/v1
kind: Deployment
metadata:
  name: widget-deployment
  namespace: local-demo-widget-ns
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: widget-deployment
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: widget-deployment
    spec:
      containers:
        - name: widget-app
          image: widget-app:1.0.0
          resources:
            requests:
              cpu: 50m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 64Mi