bases:
- ../../widget-base

generatorOptions:
  disableNameSuffixHash: true

patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: widget-deployment
  path: nodeselector-patch.yaml